import { nextTick } from "vue";

export function useBlindPrinter(store, userStore, stageRef, scale) {
  
  async function printBlinds() {
    const blinds = store.mapData.blinds;
    if (!blinds || blinds.length === 0) {
      alert("No blinds found. Please setup blinds first.");
      return;
    }

    // 1. Snapshot current state to restore later
    const originalHides = JSON.parse(JSON.stringify(store.hides));
    const originalScale = scale.value;
    const originalStep = store.gridStep;
    const originalLayer = store.currentLayer;
    const originalShowHides = store.showHides;

    // 2. Prepare Stage (High Res, No Grid)
    store.clearSelection();
    scale.value = 40; 
    store.gridStep = 1; // Effectively hides grid
    store.currentLayer = 1; 
    store.showHides = true;

    await nextTick();
    const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
    await wait(200);

    const pages = [];

    // 3. Loop through Blinds
    for (const blind of blinds) {
      // Inject this blind's hides into the store
      store.hides = blind.hides;
      
      await nextTick();
      await wait(150); // Wait for render

      // Capture Stage
      const imgData = await stageRef.value.getStage().toDataURL({ pixelRatio: 2 });
      
      pages.push({
        name: blind.name,
        randoms: blind.randoms,
        img: imgData
      });
    }

    // 4. Restore Original State
    store.hides = originalHides;
    scale.value = originalScale;
    store.gridStep = originalStep;
    store.currentLayer = originalLayer;
    store.showHides = originalShowHides;

    // 5. Generate HTML
    const pagesHtml = pages.map(p => `
      <div class="print-page">
        <div class="header">
          <div class="title-section">
            <h1>${store.mapName}</h1>
            <h2>${p.name}</h2>
          </div>
          <div class="meta-section">
            <div class="randoms-box">
              <span class="label">Randoms:</span>
              <span class="values">${p.randoms.join(" - ")}</span>
            </div>
            <div class="judge-info">Judge: ${userStore.judgeName || "________________"}</div>
          </div>
        </div>
        <div class="map-container">
          <img src="${p.img}" />
        </div>
        <div class="footer">Generated by K9CourseBuilder.com</div>
      </div>
    `).join("");

    // 6. Open Print Window
    const win = window.open("", "_blank");
    win.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Blind Export - ${store.mapName}</title>
          <style>
            @media print { 
              @page { size: landscape; margin: 0; } 
              body { -webkit-print-color-adjust: exact; }
            }
            body { font-family: 'Segoe UI', sans-serif; margin: 0; background: #fff; color: #333; }
            .print-page { 
              height: 100vh; width: 100vw; 
              page-break-after: always; 
              display: flex; flex-direction: column; 
              padding: 20px; box-sizing: border-box;
            }
            .header { 
              display: flex; justify-content: space-between; align-items: center; 
              border-bottom: 2px solid #333; padding-bottom: 15px; margin-bottom: 10px;
            }
            .title-section h1 { margin: 0; font-size: 24px; }
            .title-section h2 { margin: 5px 0 0 0; font-size: 32px; color: #2196f3; }
            .meta-section { text-align: right; display: flex; flex-direction: column; align-items: flex-end; gap: 10px; }
            .randoms-box { 
              border: 2px solid #333; padding: 8px 20px; border-radius: 8px; 
              background: #f5f5f5; display: flex; align-items: center; gap: 10px;
            }
            .randoms-box .label { text-transform: uppercase; font-size: 12px; font-weight: bold; color: #666; }
            .randoms-box .values { font-size: 24px; font-weight: bold; font-family: monospace; letter-spacing: 2px; }
            .map-container { 
              flex: 1; display: flex; justify-content: center; align-items: center; 
              overflow: hidden; border: 1px solid #eee; margin: 10px 0;
            }
            img { max-width: 100%; max-height: 100%; object-fit: contain; }
            .footer { font-size: 10px; color: #999; text-align: center; }
          </style>
        </head>
        <body>${pagesHtml}</body>
      </html>
    `);
    win.document.close();
    setTimeout(() => {
      win.focus();
      win.print();
    }, 500);
  }

  return { printBlinds };
}