import { nextTick } from "vue";

export function useBlindPrinter(store, userStore, stageRef, scale) {
  
  async function printBlinds() {
    const blinds = store.mapData.blinds;
    if (!blinds || blinds.length === 0) {
      alert("No blinds found. Please setup blinds first.");
      return;
    }

    // 1. OPEN WINDOW IMMEDIATELY
    // This must happen synchronously to bypass popup blockers.
    const win = window.open("", "_blank");
    
    // Safety check: Did the browser block it?
    if (!win) {
      alert("Please allow popups for this site to print.");
      return;
    }

    // 2. SHOW LOADING STATE
    // Give the user feedback while the screenshots are being taken
    win.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Generating Printables...</title>
          <style>
            body { 
              font-family: 'Segoe UI', sans-serif; 
              display: flex; flex-direction: column; 
              align-items: center; justify-content: center; 
              height: 100vh; margin: 0; background: #f5f5f5; color: #333;
            }
            .loader {
              border: 8px solid #e0e0e0;
              border-top: 8px solid #2196f3;
              border-radius: 50%;
              width: 60px; height: 60px;
              animation: spin 1s linear infinite;
              margin-bottom: 20px;
            }
            @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
            h2 { margin-top: 0; }
            p { color: #666; }
          </style>
        </head>
        <body>
          <div class="loader"></div>
          <h2>Generating Map Package</h2>
          <p>Please wait while we capture high-resolution images...</p>
        </body>
      </html>
    `);

    try {
      // 3. SNAPSHOT CURRENT STATE
      const originalHides = JSON.parse(JSON.stringify(store.hides));
      const originalScale = scale.value;
      const originalStep = store.gridStep;
      const originalLayer = store.currentLayer;
      const originalShowHides = store.showHides;
      
      // Snapshot the Stage Position (Pan)
      const stage = stageRef.value.getStage();
      const originalStagePos = stage.position();

      // 4. PREPARE STAGE (High Res, No Grid)
      store.clearSelection();
      scale.value = 40; 
      store.gridStep = 1; 
      store.currentLayer = 1; 
      store.showHides = true;

      // Calculate dimensions
      const GRID_OFFSET = 30;
      const cleanW = Number(store.ringDimensions.width) || 24;
      const cleanH = Number(store.ringDimensions.height) || 24;
      
      const totalWidth = cleanW * scale.value + (GRID_OFFSET * 2);
      const totalHeight = cleanH * scale.value + (GRID_OFFSET * 2);

      await nextTick();
      const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
      await wait(200);

      const pages = [];

      // 5. CAPTURE LOOP
      for (const blind of blinds) {
        store.hides = blind.hides;
        
        await nextTick();
        await wait(150); 

        // Force Stage to (0,0) right before capture to override auto-panning
        stage.position({ x: 0, y: 0 });

        // Capture Stage
        const imgData = await stage.toDataURL({ 
          pixelRatio: 2,
          x: 0,
          y: 0,
          width: totalWidth,
          height: totalHeight
        });
        
        pages.push({
          name: blind.name,
          randoms: blind.randoms,
          img: imgData
        });
      }

      // 6. RESTORE ORIGINAL STATE
      store.hides = originalHides;
      scale.value = originalScale;
      store.gridStep = originalStep;
      store.currentLayer = originalLayer;
      store.showHides = originalShowHides;
      
      // Restore user's pan position
      stage.position(originalStagePos);

      // 7. GENERATE FINAL HTML
      const pagesHtml = pages.map(p => `
        <div class="print-page">
          <div class="header">
            <div class="title-section">
              <h1>${store.mapName}</h1>
              <h2>${p.name}</h2>
            </div>
            <div class="meta-section">
              <div class="randoms-box">
                <span class="label">Randoms:</span>
                <span class="values">${p.randoms.join(" - ")}</span>
              </div>
              <div class="judge-info">Judge: ${userStore.judgeName || "________________"}</div>
            </div>
          </div>
          <div class="map-container">
            <img src="${p.img}" />
          </div>
          <div class="footer">Generated by K9CourseBuilder.com</div>
        </div>
      `).join("");

      // 8. INJECT CONTENT INTO WINDOW
      // We explicitly call open() to clear the previous "Loading" document
      win.document.open();
      win.document.write(`
        <!DOCTYPE html>
        <html>
          <head>
            <title>Blind Export - ${store.mapName}</title>
            <style>
              @media print { 
                @page { size: landscape; margin: 0; } 
                body { -webkit-print-color-adjust: exact; }
              }
              body { font-family: 'Segoe UI', sans-serif; margin: 0; background: #fff; color: #333; }
              .print-page { 
                height: 100vh; width: 100vw; 
                page-break-after: always; 
                display: flex; flex-direction: column; 
                padding: 20px; box-sizing: border-box;
              }
              .header { 
                display: flex; justify-content: space-between; align-items: center; 
                border-bottom: 2px solid #333; padding-bottom: 15px; margin-bottom: 10px;
              }
              .title-section h1 { margin: 0; font-size: 24px; }
              .title-section h2 { margin: 5px 0 0 0; font-size: 32px; color: #2196f3; }
              .meta-section { text-align: right; display: flex; flex-direction: column; align-items: flex-end; gap: 10px; }
              .randoms-box { 
                border: 2px solid #333; padding: 8px 20px; border-radius: 8px; 
                background: #f5f5f5; display: flex; align-items: center; gap: 10px;
              }
              .randoms-box .label { text-transform: uppercase; font-size: 12px; font-weight: bold; color: #666; }
              .randoms-box .values { font-size: 24px; font-weight: bold; font-family: monospace; letter-spacing: 2px; }
              .map-container { 
                flex: 1; display: flex; justify-content: center; align-items: center; 
                overflow: hidden; border: 1px solid #eee; margin: 10px 0;
              }
              img { max-width: 100%; max-height: 100%; object-fit: contain; }
              .footer { font-size: 10px; color: #999; text-align: center; }
            </style>
          </head>
          <body>${pagesHtml}</body>
        </html>
      `);
      win.document.close();
      
      // Give the images a split second to render in the new window before triggering print
      setTimeout(() => {
        win.focus();
        win.print();
      }, 500);

    } catch (e) {
      console.error(e);
      // If something broke, tell the user in the window we already opened
      win.document.body.innerHTML = `
        <h2 style="color: red; text-align: center; margin-top: 50px;">Error Generating Print</h2>
        <p style="text-align: center;">${e.message}</p>
      `;
    }
  }

  return { printBlinds };
}