import { nextTick } from "vue";

export function usePrinter(store, userStore, stageRef, scale) {
  // Helper to wait
  const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

  async function handlePrint(configOrBool = true, orientation = "landscape") {
    // 1. Normalize Configuration
    let config = {
      layers: [1, 2, 3],
      withHides: true,
      layout: "full",
      overlayAll: false,
      randoms: null,
    };

    if (typeof configOrBool === "boolean") {
      config.withHides = configOrBool;
    } else {
      config = { ...config, ...configOrBool };
    }

    // 2. Setup Watermark
    const isPro = userStore.isPro;
    const watermarkHtml = !isPro
      ? `<div class="watermark">DRAFT - UPGRADE TO REMOVE</div>`
      : "";

    // 3. Prepare Stage
    // Store original state
    const originalScale = scale.value;
    const originalStep = store.gridStep;
    const originalLayer = store.currentLayer;
    const originalShowHides = store.showHides;
    const originalMultiView = store.multiLayerView;

    try {
      store.clearSelection();
      
      // [FIX] Use slightly lower scale/ratio to prevent GPU crash
      // Scale 35 + pixelRatio 2 = 70px per foot (High Quality)
      // vs Scale 40 + pixelRatio 3 = 120px per foot (Overkill/Crash)
      scale.value = 35; 
      store.gridStep = 1;

      // [FIX] Give browser breathing room to handle the massive resize
      await nextTick();
      await wait(500); // Wait 0.5s for the white screen to resolve

      // 4. HTML Helpers (Header/Legend) - Kept largely same
      const logoHtml = userStore.clubLogoUrl
        ? `<img src="${userStore.clubLogoUrl}" class="print-logo" />`
        : "";
      const clubName = store.trialLocation || userStore.clubName;
      const clubHtml = clubName
        ? `<div class="meta"><strong>Club:</strong> ${clubName}</div>`
        : "";

      const getHeader = (subtitleSuffix = "", isCompact = false) => {
        if (isCompact) {
          let meta = store.classLevel || "";
          if (store.trialNumber) meta += ` | T${store.trialNumber}`;
          if (store.trialDay) meta += ` | ${store.trialDay}`;

          return `
            <div class="header compact">
              <div class="compact-row">
                 <h1 class="compact-title">${store.mapName}</h1>
                 <div class="compact-meta">${meta}</div>
              </div>
              <div class="compact-row secondary">
                 <div><strong>Judge:</strong> ${userStore.judgeName || "________"}</div>
                 <div><strong>Club:</strong> ${store.trialLocation}</div>
              </div>
            </div>
           `;
        }

        let subtitle = store.classLevel;
        if (store.trialNumber) subtitle += ` Trial ${store.trialNumber}`;
        if (store.trialDay) subtitle += `, ${store.trialDay}`;
        if (subtitleSuffix) subtitle += ` ${subtitleSuffix}`;

        if (!store.trialNumber && !store.trialDay) {
          subtitle = `${store.classLevel} Barn Hunt ${subtitleSuffix}`;
        }

        return `
        <div class="header">
          <div class="header-left">
            ${logoHtml}
            <div class="title-block">
              <h1>${store.mapName}</h1>
              <h2>${subtitle}</h2>
            </div>
          </div>
          <div class="header-right">
            <div class="meta"><strong>Judge:</strong> ${userStore.judgeName || "__________________"}</div>
            ${clubHtml}
            <div class="meta"><strong>Size:</strong> ${store.ringDimensions.width}' x ${store.ringDimensions.height}'</div>
            <div class="sub-meta">Generated by K9CourseBuilder.com</div>
          </div>
        </div>
        `;
      };

      const getMiniLegend = () => `
        <div class="mini-legend">
        <div class="legend-item"><span class="symbol layer-1"></span>L1</div>
          <div class="legend-item"><span class="symbol layer-2"></span>L2</div>
          <div class="legend-item"><span class="symbol layer-3"></span>L3</div>
          <div class="legend-item"><span class="symbol flat"></span> Flat</div>
          <div class="legend-item"><span class="symbol tall"></span> Tall</div>
          <div class="legend-item"><span class="symbol pillar"></span> Pillar</div>
          <div class="legend-item"><span class="symbol leaner">→</span> Lean</div>
          </div>
        <div class="mini-legend">
          <div class="legend-item"><span class="symbol hide-rat">R</span> Rat</div>
          <div class="legend-item"><span class="symbol hide-litter">L</span> Litter</div>
          <div class="legend-item"><span class="symbol hide-empty">E</span> Empty</div>
          <div class="legend-item"><span class="symbol hide-rat-under">R</span>Below</div>
          <div class="legend-item">
            <svg width="24" height="12" style="margin-right:4px">
               <circle cx="4" cy="6" r="3" fill="#2e7d32" stroke="#2e7d32" stroke-width="2" />
               <circle cx="20" cy="6" r="3" fill="#2e7d32" stroke="#2e7d32" stroke-width="2" />
               <line x1="7" y1="6" x2="17" y2="6" stroke="#2e7d32" stroke-width="2" />
            </svg>
            Edge
          </div> 
        </div>
      `;

      const getDiffHtml = () => {
        const diffs = store.differentials;
        if (!diffs) return "";

        const fmt = (l) => {
          const d = diffs[l];
          if (!d) return "";
          const sign = d.net > 0 ? "+" : "";
          const movedText = d.moved > 0 ? `, ${d.moved} moved` : "";
          return `<div><strong>L${l}:</strong> ${sign}${d.net}${movedText}</div>`;
        };

        const totalSign = diffs.totalNet > 0 ? "+" : "";
        const comparisonName = store.comparisonMapName
          ? `<div style="color: #d32f2f; font-style: italic; margin-bottom: 2px;">${store.comparisonMapName}</div>`
          : "";

        return `
          <div class="legend-sub-section">
            <h4 style="margin-bottom: 2px;">Changes vs. Previous</h4>
            <div style="font-size: 10px; line-height: 1.2;">
              ${comparisonName}
              <div style="border-bottom: 1px solid #eee; margin-bottom: 2px; padding-bottom: 2px;">
                  <strong>TOTAL:</strong> ${totalSign}${diffs.totalNet} Bales
              </div>
              ${fmt(1)}
              ${fmt(2)}
              ${fmt(3)}
            </div>
          </div>
        `;
      };

      const getLegendHtml = () => `
        <div class="legend-sidebar">
          <h3>Legend</h3>
          ${
            isPro
              ? `
          <div class="legend-section">
            <h4>Statistics</h4>
            <div class="stats-grid">
              <div class="legend-item"><strong>Total: ${store.inventory.total}</strong></div>
              <div class="legend-item" style="color:#e6c200"><strong>L1:</strong> ${store.inventory.base}</div>
              <div class="legend-item" style="color:#4caf50"><strong>L2:</strong> ${store.inventory.layer2}</div>
              <div class="legend-item" style="color:#2196f3"><strong>L3:</strong> ${store.inventory.layer3}</div>
            </div>
            ${getDiffHtml()}
          </div>
          `
              : `
          <div class="legend-section" style="opacity: 0.6; border: 1px dashed #ccc; padding: 4px; background: #f9f9f9;">
            <h4 style="margin-bottom: 2px;">Statistics</h4>
            <div style="font-size: 9px; font-style: italic;">
               Bale counts & Change log<br>available in Founder's Tier.
            </div>
          </div>
          `
          }
          <div class="legend-section">
            <h4>Bales & Orientation</h4>
            <div class="legend-grid">
              <div class="legend-item"><span class="symbol layer-1"></span> L1 (Base)</div>
              <div class="legend-item"><span class="symbol flat"></span> Flat</div>
              <div class="legend-item"><span class="symbol layer-2"></span> L2</div>
              <div class="legend-item"><span class="symbol tall"></span> Tall</div>
              <div class="legend-item"><span class="symbol layer-3"></span> L3</div>
              <div class="legend-item"><span class="symbol pillar"></span> Pillar</div>
            </div>
          </div>
          <div class="legend-section">
            <h4>Features & Bounds</h4>
            <div class="legend-grid">
              <div class="legend-item"><span class="symbol fence"></span> Fence</div>
              <div class="legend-item"><span class="symbol wall"></span> Wall</div>
              <div class="legend-item"><span class="symbol tunnel"></span>Board Edge</div>
              <div class="legend-item"><span class="symbol tunnelbox"></span>Board Box</div>
              <div class="legend-item"><span class="symbol gate"></span> Gate</div>
              <div class="legend-item"><span class="symbol step"></span> Step</div>
              <div class="legend-item"><span class="symbol leaner">→</span> Leaner</div>
              <div class="legend-item"><span class="symbol anchor">⚓</span> Anchor Bale</div>
              <div class="legend-item"><span class="symbol start"></span> Start</div>
              <div class="legend-item"><span class="symbol dc"></span> DC Mat</div>
              <div class="legend-item"><span class="symbol obstruction"></span> Obstr.</div>
              <div class="legend-item"><span class="symbol dead-zone"></span> Dead Zone</div>
            </div>
          </div>
          <div class="legend-section">
            <h4>Hides</h4>
            <div class="legend-grid">
              <div class="legend-item"><span class="symbol hide-rat">R</span> Rat</div>
              <div class="legend-item"><span class="symbol hide-litter">L</span> Litter</div>
              <div class="legend-item"><span class="symbol hide-empty">E</span> Empty</div>
              <div class="legend-item"><span class="symbol hide-rat-under"> </span> (Under)</div>
            </div>
          </div>
        </div>
      `;

      const printStyles = `
        * { -webkit-print-color-adjust: exact !important; print-color-adjust: exact !important; color-adjust: exact !important; }
        html, body { margin: 0; padding: 0; width: 100%; height: 100%; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; }
        .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%) rotate(-45deg); font-size: 80px; font-weight: bold; color: rgba(0, 0, 0, 0.08); z-index: 9999; pointer-events: none; white-space: nowrap; user-select: none; width: 100%; text-align: center; }
        .print-page { height: 98vh; width: 100%; display: flex; flex-direction: column; break-after: page; page-break-after: always; position: relative; }
        .print-page:last-child { break-after: auto; page-break-after: auto; }
        .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; padding-left: 15px; padding-right: 15px; }
        .header-left { display: flex; align-items: center; gap: 15px; }
        .print-logo { height: 60px; width: auto; object-fit: contain; }
        .title-block { display: flex; align-items: center; gap: 15px; margin-left: 5px; }
        .title-block h2 { margin: 0; font-size: 16px; font-weight: normal; color: #666; }
        .header-right { text-align: right; margin-right: 5px; }
        .meta { font-size: 1rem; line-height: 1.4; }
        .sub-meta { font-size: 11px; color: #888; margin-top: 4px; }
        .page-body { flex: 1; display: flex; min-height: 0; gap: 20px; }
        .map-container { flex: 1; display: flex; justify-content: center; align-items: flex-start; overflow: hidden; }
        img.map-img { max-width: 100%; max-height: 100%; object-fit: contain; border: 1px solid #eee; }
        .legend-sidebar { width: 175px; flex-shrink: 0; border-left: 1px solid #ccc; padding-left: 15px; font-size: 11px; }
        .legend-sidebar h3 { margin: 0 0 8px 0; font-size: 14px; text-transform: uppercase; border-bottom: 1px solid #333; display: inline-block; }
        .legend-section { margin-bottom: 10px; }
        .legend-section h4 { margin: 0 0 4px 0; font-size: 11px; color: #666; text-transform: uppercase; border-bottom: 1px solid #eee; }
        .legend-sub-section { border-top: 1px solid #ddd; padding-top: 4px; margin-top: 4px; }
        .stats-grid, .legend-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 2px 5px; }
        .legend-item { display: flex; align-items: center; gap: 6px; line-height: 1.2; font-size: 10px; }
        .symbol { display: inline-block; width: 16px; height: 10px; border: 1px solid black; position: relative; flex-shrink: 0; }
        .layer-1 { background: #e6c200; }
        .layer-2 { background: #4caf50; }
        .layer-3 { background: #2196f3; }
        .flat { background: #fff; }
        .tall { background: linear-gradient(to bottom right, transparent 46%, black 47%, black 53%, transparent 54%); background-color: #fff; }
        .pillar { background: linear-gradient(to bottom right, transparent 46%, black 47%, black 53%, transparent 54%), linear-gradient(to bottom left, transparent 46%, black 47%, black 53%, transparent 54%); background-color: #fff; }
        .anchor { border: 2px solid #d32f2f; color: #d32f2f; font-weight: bold; text-align: center; line-height: 8px; font-size: 10px; border-radius: 2px; background: white; }
        .tunnel { height: 4px; background: #2e7d32; border: none; }
        .tunnelbox { height: 6px; background: rgba(139, 69, 19, 0.4); border: 1px solid brown; }
        .leaner { border: none; font-size: 12px; font-weight: bold; width: auto; height: auto; }
        .start { border: 1px solid black; background: #eee; }
        .dc { background: #d1c4e9; }
        .step { background: #8D6E63; border: 1px solid black;}
        .obstruction { border: 1px dashed black; background: rgba(100, 100, 100, 0.5); }
        .dead-zone { border: 1px dashed red; background: rgba(255, 0, 0, 0.3); }
        .fence { border: 1px solid black; background-color: transparent; }
        .wall { background-color: #333; border: 1px solid black; box-shadow: inset 0 0 0 4px #333; }
        .hide-rat, .hide-litter, .hide-empty, .hide-rat-under { width: 16px; height: 16px; border-radius: 50%; border: 2px solid black; text-align: center; line-height: 12px; font-size: 11px; font-weight: bold; }
        .hide-rat { background: red; color: black; }
        .hide-rat-under { color: black; stroke-width: 2; border-style: dashed; }
        .hide-litter { background: yellow; color: black; }
        .hide-empty { background: white; color: black; }
        .quarter-grid { display: grid; grid-template-columns: 1fr 1fr; grid-template-rows: 1fr 1fr; height: 100%; width: 100%; gap: 10px; box-sizing: border-box; }
        .quarter-item { border: 1px dashed #ccc; padding: 10px; display: flex; flex-direction: column; overflow: hidden; }
        .quarter-item .map-img-wrapper { flex: 1; display: flex; justify-content: center; align-items: center; overflow: hidden; min-height: 0; }
        .quarter-item img { max-width: 98%; max-height: 98%; object-fit: contain; }
        .header.compact { border-bottom: 1px solid #999; padding-bottom: 5px; margin-bottom: 5px; display: flex; flex-direction: column; gap: 4px; align-items: stretch; }
        .compact-row { display: flex; justify-content: space-between; align-items: baseline; }
        .compact-title { font-size: 16px; margin: 0; font-weight: bold; }
        .compact-meta { font-size: 12px; color: #444; }
        .compact-row.secondary { font-size: 11px; border-top: 1px solid #eee; padding-top: 4px; }
        .mini-legend { display: flex; justify-content: center; flex-wrap: wrap; gap: 8px 12px; border-top: 1px solid #ccc; padding-top: 6px; margin-top: 8px; }
        .mini-legend .legend-item { font-size: 10px; }
        .mini-legend .symbol { width: 12px; height: 12px; line-height: 10px; font-size: 9px; }
        .randoms-page .randoms-body { column-count: 2; column-gap: 40px; padding: 20px; font-size: 14px; }
        .trial-block { break-inside: avoid; margin-bottom: 30px; border: 1px solid #eee; padding: 15px; border-radius: 4px; }
        .trial-title { font-size: 18px; font-weight: bold; border-bottom: 2px solid #333; margin-bottom: 10px; }
        .blind-row { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #eee; }
        .blind-numbers { font-family: monospace; font-size: 16px; font-weight: bold; letter-spacing: 2px; }
      `;

      const hideCss = !config.withHides
        ? `.hide-rat, .hide-litter, .hide-empty, .hide-rat-under { display: none !important; }`
        : "";

      // 5. Capture Logic (Fixed for Reliability)
      const pages = [];

      const captureLayer = async (layerNum) => {
        store.currentLayer = layerNum;
        store.showHides = config.withHides;
        store.multiLayerView = config.overlayAll ? layerNum : false;

        // Wait for Vue to update the DOM
        await nextTick();
        
        // Wait for Konva to render the heavy layer
        await wait(300);

        // [FIX] Force Konva to flush all draw operations synchronously
        const stage = stageRef.value.getStage();
        stage.batchDraw();
        
        // Wait another tick to ensure batchDraw is painted
        await wait(50); 

        // [FIX] Reduce pixelRatio to 2 to prevent "White Screen" crashes on large canvases
        return stage.toDataURL({ pixelRatio: 2 });
      };

      for (const layerNum of config.layers) {
        // Only print layer if it exists or is Layer 1
        const hasItems = layerNum === 1 || store.bales.some((b) => b.layer === layerNum);
        if (hasItems) {
          const imgData = await captureLayer(layerNum);
          pages.push({ title: `• Layer ${layerNum}`, img: imgData });
        }
      }

      // 6. Generate HTML
      let pagesHtml = "";

      if (config.layout === "full") {
        pagesHtml = pages.map((p) => `
          <div class="print-page">
            ${watermarkHtml}
            ${getHeader(p.title)}
            <div class="page-body">
              <div class="map-container"><img src="${p.img}" class="map-img" /></div>
              ${getLegendHtml()}
            </div>
          </div>
        `).join("");
      } else if (config.layout === "quarter") {
        pagesHtml = pages.map((p) => `
          <div class="print-page">
            ${watermarkHtml}
            <div class="quarter-grid">
              ${Array(4).fill(0).map(() => `
                <div class="quarter-item">
                  ${getHeader(p.title, true)}
                  <div class="map-img-wrapper"><img src="${p.img}" /></div>
                  ${getMiniLegend()}
                </div>
              `).join("")}
            </div>
          </div>
        `).join("");
      }

      // Randoms Page
      if (config.randoms) {
        const { trials, blinds } = config.randoms;
        let randomsHtml = "";
        for (let t = 1; t <= trials; t++) {
          randomsHtml += `<div class="trial-block"><div class="trial-title">Trial ${t}</div>`;
          for (let b = 1; b <= blinds; b++) {
            const nums = Array(5).fill(0).map(() => Math.floor(Math.random() * 5) + 1);
            randomsHtml += `
              <div class="blind-row">
                <span class="blind-label">Blind ${b}</span>
                <span class="blind-numbers">${nums.join(" - ")}</span>
              </div>`;
          }
          randomsHtml += `</div>`;
        }
        pagesHtml += `
          <div class="print-page randoms-page">
            ${watermarkHtml}
            <div class="header">
               <div class="title-block"><h1>Master Blind Randoms</h1></div>
               <div class="header-right"><div class="meta"><strong>Judge:</strong> ${userStore.judgeName || "___"}</div></div>
            </div>
            <div class="randoms-body">${randomsHtml}</div>
          </div>
        `;
      }

      // 7. Write to Window
      const win = window.open("", "_blank");
      if (win) {
        win.document.write(`
          <!DOCTYPE html>
          <html>
            <head>
              <title>${store.mapName}</title>
              <style>
                @media print { @page { size: ${orientation}; margin: 0; } }
                ${printStyles}
                ${hideCss}
              </style>
            </head>
            <body>${pagesHtml}</body>
          </html>
        `);
        win.document.close();
        setTimeout(() => {
          win.focus();
          win.print();
        }, 500);
      }
    } catch (e) {
      console.error("Print Failed", e);
      alert("Print failed. Please try again or use the 'Take Screenshot' tool.");
    } finally {
      // 8. Restore State ALWAYS
      store.currentLayer = originalLayer;
      store.showHides = originalShowHides;
      scale.value = originalScale;
      store.gridStep = originalStep;
      store.multiLayerView = originalMultiView;
    }
  }

  return { handlePrint };
}