import { nextTick } from 'vue'

export function usePrinter(store, userStore, stageRef, scale) {
  
  async function handlePrint(withHides = true) {
    const originalScale = scale.value
    scale.value = 40 // Force standard print resolution
    await nextTick()
    const wait = (ms) => new Promise(resolve => setTimeout(resolve, ms))
    await wait(100) 

    const d = new Date().toLocaleDateString()
    const logoHtml = userStore.clubLogoUrl ? `<img src="${userStore.clubLogoUrl}" class="print-logo" />` : ''
    
    // --- UPDATED: Use Trial Location if available, else fallback to user profile club name ---
    const clubName = store.trialLocation || userStore.clubName
    const clubHtml = clubName ? `<div class="meta"><strong>Club:</strong> ${clubName}</div>` : ''

    // --- UPDATED: Construct Subtitle ---
    // If we have Trial info, use the requested format: "{{Class}} Trial {{Number}}, {{Day}} - {{Layer}}"
    // Otherwise fall back to the old format.
    const getSubtitle = (layerName) => {
      if (store.trialNumber || store.trialDay) {
        let text = `${store.classLevel}`
        if (store.trialNumber) text += ` Trial ${store.trialNumber}`
        if (store.trialDay) text += `, ${store.trialDay}`
        
        // Append Layer info
        if (layerName) text += ` - ${layerName.replace('• ', '')}` 
        return text
      } else {
        // Fallback
        return `${store.classLevel} ${store.sport === 'agility' ? 'Agility' : 'Barn Hunt'} ${layerName || ''}`
      }
    }

    // Shared Header
    const getHeader = (subtitleSuffix = '') => `
      <div class="header">
        <div class="header-left">
          ${logoHtml}
          <div class="title-block">
            <h1>${store.mapName}</h1>
            <h2>${getSubtitle(subtitleSuffix)}</h2>
          </div>
        </div>
        <div class="header-right">
          <div class="meta"><strong>Judge:</strong> ${userStore.judgeName || '__________________'}</div>
          ${clubHtml}
          <div class="meta"><strong>Size:</strong> ${store.ringDimensions.width}' x ${store.ringDimensions.height}'</div>
          <div class="sub-meta">Generated by K9CourseBuilder.com</div>
        </div>
      </div>
    `

    const printStyles = `
      @page { size: landscape; margin: 0.25in; }
      html, body { margin: 0; padding: 0; width: 100%; }
      body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; }
      .print-page { height: 98vh; width: 100%; display: flex; flex-direction: column; break-after: page; page-break-after: always; }
      .print-page:last-child { break-after: auto; page-break-after: auto; }
      .header { flex: 0 0 auto; display: flex; justify-content: space-between; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 10px; }
      .header-left { display: flex; align-items: center; gap: 15px; }
      .print-logo { height: 60px; width: auto; object-fit: contain; }
      .title-block h1 { margin: 0; font-size: 24px; line-height: 1.2; color: #000; }
      .title-block h2 { margin: 0; font-size: 16px; font-weight: normal; color: #666; }
      .header-right { text-align: right; }
      .meta { font-size: 14px; margin-bottom: 2px; }
      .sub-meta { font-size: 11px; color: #888; margin-top: 4px; }
      .map-container { flex: 1; min-height: 0; display: flex; justify-content: center; align-items: center; overflow: hidden; }
      img.map-img { max-width: 100%; max-height: 100%; object-fit: contain; border: 1px solid #eee; }
    `

    // AGILITY
    if (store.sport === 'agility') {
      const dataUrl = stageRef.value.getStage().toDataURL({ pixelRatio: 3 })
      scale.value = originalScale 
      
      const win = window.open('', '_blank')
      win.document.write(`<!DOCTYPE html><html><head><title>${store.mapName}</title><style>${printStyles}</style></head><body><div class="print-page">${getHeader('')}<div class="map-container"><img src="${dataUrl}" class="map-img"/></div></div></body></html>`)
      win.document.close()
      setTimeout(() => { win.focus(); win.print(); }, 500);
      return
    }

    // BARN HUNT (Multi-Page)
    const originalLayer = store.currentLayer
    const pages = []

    const shouldPrintLayer = (layerNum) => {
      if (layerNum === 1) return true
      return store.bales.some(b => b.layer === layerNum)
    }
    
    if (shouldPrintLayer(1)) {
      store.currentLayer = 1; await wait(150);
      pages.push({ title: '• Layer 1', img: stageRef.value.getStage().toDataURL({ pixelRatio: 3 }) })
    }
    
    if (shouldPrintLayer(2)) {
      store.currentLayer = 2; await wait(150);
      pages.push({ title: '• Layer 2', img: stageRef.value.getStage().toDataURL({ pixelRatio: 3 }) })
    }
    
    if (shouldPrintLayer(3)) {
      store.currentLayer = 3; await wait(150);
      pages.push({ title: '• Layer 3', img: stageRef.value.getStage().toDataURL({ pixelRatio: 3 }) })
    }

    store.currentLayer = originalLayer
    scale.value = originalScale

    const pagesHtml = pages.map(p => `
      <div class="print-page">
        ${getHeader(p.title)}
        <div class="map-container">
          <img src="${p.img}" class="map-img" />
        </div>
      </div>
    `).join('')

    const win = window.open('', '_blank')
    win.document.write(`
      <!DOCTYPE html>
      <html>
        <head><title>${store.mapName}</title><style>${printStyles}</style></head>
        <body>${pagesHtml}</body>
      </html>
    `)
    win.document.close()
    setTimeout(() => { win.focus(); win.print(); }, 500);
  }

  return { handlePrint }
}