import { nextTick } from 'vue'

export function usePrinter(store, userStore, stageRef, scale) {

  // [UPDATED] Accepts a config object OR a boolean (for backward compatibility)
  async function handlePrint(configOrBool = true) {
    
    // 1. Normalize Configuration
    let config = { 
      layers: [1, 2, 3], 
      withHides: true, 
      layout: 'full' // 'full' or 'quarter'
    }

    if (typeof configOrBool === 'boolean') {
      config.withHides = configOrBool
    } else {
      config = { ...config, ...configOrBool }
    }

    // 2. Setup Watermark (The Gate)
    // We use the getter we added to userStore in Phase 2
    const isPro = userStore.isPro 
    const watermarkHtml = !isPro 
      ? `<div class="watermark">DRAFT - UPGRADE TO REMOVE</div>` 
      : ''

    // 3. Prepare Stage (Zoom in for high-res capture)
    store.clearSelection()
    const originalScale = scale.value
    scale.value = 40 // Force standard print resolution (high quality)
    const originalStep = store.gridStep
    store.gridStep = 1 // Hide grid dots usually, or make them fine
    await nextTick()
    
    // Slight delay to ensure canvas renders at new scale
    const wait = (ms) => new Promise(resolve => setTimeout(resolve, ms))
    await wait(100)

    // 4. HTML Helpers
    const logoHtml = userStore.clubLogoUrl ? `<img src="${userStore.clubLogoUrl}" class="print-logo" />` : ''
    const clubName = store.trialLocation || userStore.clubName
    const clubHtml = clubName ? `<div class="meta"><strong>Club:</strong> ${clubName}</div>` : ''

    // [UPDATED] Header Generator (Supports Full & Compact)
    const getHeader = (subtitleSuffix = '', isCompact = false) => {
      // Quarter Page Header
      if (isCompact) {
         return `
          <div class="header compact">
            <div class="title-block">
               <h1>${store.mapName} ${subtitleSuffix}</h1>
            </div>
             <div class="meta-compact">Judge: ${userStore.judgeName || '___'}</div>
          </div>
         `
      }

      // Full Page Header
      let subtitle = store.classLevel
      if (store.trialNumber) subtitle += ` Trial ${store.trialNumber}`
      if (store.trialDay) subtitle += `, ${store.trialDay}`
      if (subtitleSuffix) subtitle += ` ${subtitleSuffix}`

      // Fallback for other sports
      if (!store.trialNumber && !store.trialDay) {
        let sportLabel = 'Barn Hunt'
        if (store.sport === 'agility') sportLabel = 'Agility'
        if (store.sport === 'scentwork') sportLabel = 'Scent Work'
        subtitle = `${store.classLevel} ${sportLabel} ${subtitleSuffix}`
      }

      return `
      <div class="header">
        <div class="header-left">
          ${logoHtml}
          <div class="title-block">
            <h1>${store.mapName}</h1>
            <h2>${subtitle}</h2>
          </div>
        </div>
        <div class="header-right">
          <div class="meta"><strong>Judge:</strong> ${userStore.judgeName || '__________________'}</div>
          ${clubHtml}
          <div class="meta"><strong>Size:</strong> ${store.ringDimensions.width}' x ${store.ringDimensions.height}'</div>
          <div class="sub-meta">Generated by K9CourseBuilder.com</div>
        </div>
      </div>
      `
    }

    // Helper for Differentials (Changes vs Previous)
    const getDiffHtml = () => {
      const diffs = store.differentials
      if (!diffs) return ''
      
      const fmt = (l) => {
        const d = diffs[l]
        if (!d) return ''
        const sign = d.net > 0 ? '+' : ''
        const movedText = d.moved > 0 ? `, ${d.moved} moved` : '' 
        return `<div><strong>L${l}:</strong> ${sign}${d.net}${movedText}</div>`
      }
      
      const totalSign = diffs.totalNet > 0 ? '+' : ''
      const comparisonName = store.comparisonMapName 
        ? `<div style="color: #d32f2f; font-style: italic; margin-bottom: 2px;">${store.comparisonMapName}</div>` 
        : ''

      return `
        <div class="legend-sub-section">
          <h4 style="margin-bottom: 2px;">Changes vs. Previous</h4>
          <div style="font-size: 10px; line-height: 1.2;">
            ${comparisonName}
            <div style="border-bottom: 1px solid #eee; margin-bottom: 2px; padding-bottom: 2px;">
                <strong>TOTAL:</strong> ${totalSign}${diffs.totalNet} Bales
            </div>
            ${fmt(1)}
            ${fmt(2)}
            ${fmt(3)}
          </div>
        </div>
      `
    }

    // [UPDATED] Legend Generator (Hides Stats for Free Users)
    const getLegendHtml = () => `
      <div class="legend-sidebar">
        <h3>Legend</h3>
        
        ${isPro ? `
        <div class="legend-section">
          <h4>Statistics</h4>
          <div class="stats-grid">
            <div class="legend-item"><strong>Total: ${store.inventory.total}</strong></div>
            <div class="legend-item" style="color:#e6c200"><strong>L1:</strong> ${store.inventory.base}</div>
            <div class="legend-item" style="color:#4caf50"><strong>L2:</strong> ${store.inventory.layer2}</div>
            <div class="legend-item" style="color:#2196f3"><strong>L3:</strong> ${store.inventory.layer3}</div>
          </div>
          ${getDiffHtml()}
        </div>
        ` : `
        <div class="legend-section" style="opacity: 0.6; border: 1px dashed #ccc; padding: 4px; background: #f9f9f9;">
          <h4 style="margin-bottom: 2px;">Statistics</h4>
          <div style="font-size: 9px; font-style: italic;">
             Bale counts & Change log<br>available in Founder's Tier.
          </div>
        </div>
        `}

        <div class="legend-section">
          <h4>Bales & Orientation</h4>
          <div class="legend-grid">
            <div class="legend-item"><span class="symbol layer-1"></span> L1 (Base)</div>
            <div class="legend-item"><span class="symbol flat"></span> Flat</div>
            <div class="legend-item"><span class="symbol layer-2"></span> L2</div>
            <div class="legend-item"><span class="symbol tall"></span> Tall</div>
            <div class="legend-item"><span class="symbol layer-3"></span> L3</div>
            <div class="legend-item"><span class="symbol pillar"></span> Pillar</div>
          </div>
        </div>

        <div class="legend-section">
          <h4>Features & Bounds</h4>
          <div class="legend-grid">
            <div class="legend-item"><span class="symbol fence"></span> Fence</div>
            <div class="legend-item"><span class="symbol wall"></span> Wall</div>
            <div class="legend-item"><span class="symbol tunnel"></span>Board Edge</div>
            <div class="legend-item"><span class="symbol tunnelbox"></span>Board Box</div>
            <div class="legend-item"><span class="symbol gate"></span> Gate</div>
            <div class="legend-item"><span class="symbol step"></span> Step</div>
            <div class="legend-item"><span class="symbol leaner">↗</span> Leaner</div>
            <div class="legend-item"><span class="symbol anchor">⚓</span> Anchor Bale</div>
            <div class="legend-item"><span class="symbol start"></span> Start</div>
            <div class="legend-item"><span class="symbol dc"></span> DC Mat</div>
            <div class="legend-item"><span class="symbol obstruction"></span> Obstr.</div>
            <div class="legend-item"><span class="symbol dead-zone"></span> Dead Zone</div>
          </div>
        </div>
        
        <div class="legend-section">
          <h4>Hides</h4>
          <div class="legend-grid">
            <div class="legend-item"><span class="symbol hide-rat">R</span> Rat</div>
            <div class="legend-item"><span class="symbol hide-litter">L</span> Litter</div>
            <div class="legend-item"><span class="symbol hide-empty">E</span> Empty</div>
            <div class="legend-item"><span class="symbol hide-rat-under"> </span> (Under)</div>
          </div>
        </div>
      </div>
    `

    // 5. CSS Styles
    const printStyles = `
      @page { size: landscape; margin: 0.25in; }
      
      * {
        -webkit-print-color-adjust: exact !important;
        print-color-adjust: exact !important;
        color-adjust: exact !important;
      }

      html, body { margin: 0; padding: 0; width: 100%; height: 100%; }
      body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; }
      
      /* Watermark - The Gate */
      .watermark {
        position: fixed;
        top: 50%; 
        left: 50%;
        transform: translate(-50%, -50%) rotate(-45deg);
        font-size: 80px;
        font-weight: bold;
        color: rgba(0, 0, 0, 0.08);
        z-index: 9999;
        pointer-events: none;
        white-space: nowrap;
        user-select: none;
        width: 100%;
        text-align: center;
      }

      .print-page { height: 98vh; width: 100%; display: flex; flex-direction: column; break-after: page; page-break-after: always; position: relative; }
      .print-page:last-child { break-after: auto; page-break-after: auto; }
      
      .header { flex: 0 0 auto; display: flex; justify-content: space-between; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 10px; }
      .header-left { display: flex; align-items: center; gap: 15px; }
      .print-logo { height: 60px; width: auto; object-fit: contain; }
      .title-block h1 { margin: 0; font-size: 24px; line-height: 1.2; color: #000; }
      .title-block h2 { margin: 0; font-size: 16px; font-weight: normal; color: #666; }
      .header-right { text-align: right; }
      .meta { font-size: 14px; margin-bottom: 2px; }
      .sub-meta { font-size: 11px; color: #888; margin-top: 4px; }

      /* Layout */
      .page-body { flex: 1; display: flex; min-height: 0; gap: 20px; }
      .map-container { flex: 1; display: flex; justify-content: center; align-items: flex-start; overflow: hidden; }
      img.map-img { max-width: 100%; max-height: 100%; object-fit: contain; border: 1px solid #eee; }

      /* Legend Styles */
      .legend-sidebar { width: 175px; flex-shrink: 0; border-left: 1px solid #ccc; padding-left: 15px; font-size: 11px; }
      .legend-sidebar h3 { margin: 0 0 8px 0; font-size: 14px; text-transform: uppercase; border-bottom: 1px solid #333; display: inline-block; }
      .legend-section { margin-bottom: 10px; }
      .legend-section h4 { margin: 0 0 4px 0; font-size: 11px; color: #666; text-transform: uppercase; border-bottom: 1px solid #eee; }
      .legend-sub-section { border-top: 1px solid #ddd; padding-top: 4px; margin-top: 4px; }
      
      .stats-grid, .legend-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 2px 5px; }
      .legend-item { display: flex; align-items: center; gap: 6px; line-height: 1.2; font-size: 10px; }
      
      .symbol { display: inline-block; width: 16px; height: 10px; border: 1px solid black; position: relative; flex-shrink: 0; }
      .layer-1 { background: #e6c200; }
      .layer-2 { background: #4caf50; }
      .layer-3 { background: #2196f3; }
      
      .flat { background: #fff; }
      .tall { background: linear-gradient(to bottom right, transparent 46%, black 47%, black 53%, transparent 54%); background-color: #fff; }
      .pillar { background: linear-gradient(to bottom right, transparent 46%, black 47%, black 53%, transparent 54%), linear-gradient(to bottom left, transparent 46%, black 47%, black 53%, transparent 54%); background-color: #fff; }

      .anchor { border: 2px solid #d32f2f; color: #d32f2f; font-weight: bold; text-align: center; line-height: 8px; font-size: 10px; border-radius: 2px; background: white; }
      .tunnel { height: 4px; background: #2e7d32; border: none; }
      .tunnelbox { height: 6px; background: rgba(139, 69, 19, 0.4); border: 1px solid brown; }
      .leaner { border: none; font-size: 12px; font-weight: bold; width: auto; height: auto; }
      .start { border: 1px dashed black; background: #eee; }
      .dc { background: #d1c4e9; }
      .step { background: #8D6E63; border: 1px solid black;}
      .obstruction { border: 1px dashed black; background: rgba(100, 100, 100, 0.5); }
      .dead-zone { border: 1px dashed red; background: rgba(255, 0, 0, 0.3); }
      .fence { height: 1px; background: black; border: none; }
      .wall { height: 6px; background: black; border: none; }
      
      .hide-rat, .hide-litter, .hide-empty, .hide-rat-under {
        width: 16px; height: 16px; border-radius: 50%; border: 2px solid black;
        text-align: center; line-height: 12px; font-size: 11px; font-weight: bold;
      }
      .hide-rat { background: red; color: black; }
      .hide-rat-under { color: black; stroke-width: 2; border-style: dashed; }
      .hide-litter { background: yellow; color: black; }
      .hide-empty { background: white; color: black; }

      /* [NEW] Quarter Layout Styles */
      .quarter-grid { 
        display: grid; 
        grid-template-columns: 1fr 1fr; 
        grid-template-rows: 1fr 1fr; 
        height: 100%; width: 100%; gap: 10px; 
        box-sizing: border-box; 
      }
      .quarter-item { 
        border: 1px dashed #ccc; padding: 10px; 
        display: flex; flex-direction: column; overflow: hidden; 
      }
      .header.compact { border-bottom: 1px solid #999; padding-bottom: 5px; margin-bottom: 5px; }
      .header.compact h1 { font-size: 14px; margin: 0; }
      .meta-compact { font-size: 10px; color: #666; }
      .quarter-item .map-img-wrapper { flex: 1; display: flex; justify-content: center; align-items: center; overflow: hidden; }
      .quarter-item img { max-width: 98%; max-height: 98%; object-fit: contain; }
    `

    // [NEW] Logic to hide hides via CSS
    const hideCss = !config.withHides ? `
      .hide-rat, .hide-litter, .hide-empty, .hide-rat-under { display: none !important; }
    ` : ''

    // 6. Handling Agility Mode (Simple Pass-through)
    if (store.sport === 'agility') {
      const dataUrl = stageRef.value.getStage().toDataURL({ pixelRatio: 3 })
      scale.value = originalScale

      const win = window.open('', '_blank')
      win.document.write(`<!DOCTYPE html><html><head><title>${store.mapName}</title><style>${printStyles}</style></head><body>
        ${watermarkHtml}
        <div class="print-page">
          ${getHeader()}
          <div class="page-body">
            <div class="map-container"><img src="${dataUrl}" class="map-img"/></div>
          </div>
        </div>
      </body></html>`)
      win.document.close()
      setTimeout(() => { win.focus(); win.print(); }, 500);
      return
    }

    // 7. Capture Selected Layers
    const originalLayer = store.currentLayer
    const pages = []

    // Helper to capture layer
    const captureLayer = async (layerNum) => {
      store.currentLayer = layerNum
      // Note: Hides are rendered by components. If we want to hide them in the IMAGE capture,
      // we would need to toggle them in the store or use a prop.
      // However, typical HTML printing relies on the captured image.
      // If we want hides GONE from the image, we rely on the logic that hides are on a separate layer
      // OR we just accept they are in the image and use the Config.withHides for the LEGEND only?
      // BETTER: If 'withHides' is false, let's toggle a class on the wrapperRef or similar before capture.
      // Since that is complex, we assume 'withHides' refers to LEGEND or we rely on the CSS injection 
      // affecting the PRINT window, but the capture happens on the CANVAS.
      // For now, we will capture what is visible. Users can toggle hides in editor if they want them off image.
      
      await wait(150)
      return stageRef.value.getStage().toDataURL({ pixelRatio: 3 })
    }

    for (const layerNum of config.layers) {
       // Only print layers that exist or are forced
       // Check if layer has items?
       const hasItems = layerNum === 1 || store.bales.some(b => b.layer === layerNum)
       if (hasItems) {
         const imgData = await captureLayer(layerNum)
         pages.push({ title: `• Layer ${layerNum}`, img: imgData })
       }
    }

    // Restore State
    store.currentLayer = originalLayer
    scale.value = originalScale
    store.gridStep = originalStep

    // 8. Generate HTML based on Layout
    let pagesHtml = ''

    if (config.layout === 'full') {
      pagesHtml = pages.map(p => `
        <div class="print-page">
          ${watermarkHtml}
          ${getHeader(p.title)}
          <div class="page-body">
            <div class="map-container">
              <img src="${p.img}" class="map-img" />
            </div>
            ${getLegendHtml()}
          </div>
        </div>
      `).join('')
    } else if (config.layout === 'quarter') {
      // 4 Copies per page layout
      pagesHtml = pages.map(p => `
        <div class="print-page">
          ${watermarkHtml}
          <div class="quarter-grid">
            ${Array(4).fill(0).map(() => `
              <div class="quarter-item">
                ${getHeader(p.title, true)}
                <div class="map-img-wrapper">
                  <img src="${p.img}" />
                </div>
              </div>
            `).join('')}
          </div>
        </div>
      `).join('')
    }

    // 9. Open Print Window
    const win = window.open('', '_blank')
    win.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${store.mapName}</title>
          <style>
            ${printStyles}
            ${hideCss} 
          </style>
        </head>
        <body>${pagesHtml}</body>
      </html>
    `)
    win.document.close()
    setTimeout(() => { win.focus(); win.print(); }, 500)
  }

  return { handlePrint }
}